### ISSUE TITLE
Setup tests

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/datapub-nhs#1]
## Aceptence criteria 
- [ ] Able to run tests without errors

## Tasks
- [ ] Install the necessary dependencies for test env
- [ ] Configure tests as we do in DataPub
