### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by kmanaseryan** [datopian/datapub-nhs#3]
## Acceptance criteria 
- [x] GH CI runs on every push to master
- [x] GH CI runs on every PR to master
- [x] Storybook is deployed to Github pages

## Tasks
- [x] Setup GH actions
- [x] Configure GH actions to deploy Storybook to GH pages
